### ISSUE TITLE
Cannot deploy JS application

### ISSUE THREAD

**Issue by msftsettiy** [microsoft/CCF#2191] opened 2021-02-10 16:53 UTC
After upgrading to v0.18.1, a JS application could not be deployed by submitting a "deploy_js_app" proposal. The first time the proposal was submitted, CCF responded with a 500 Internal server error. Following is the request details. Some data is masked with 'x'. 

_call_potentially_signed:84 - [xxxxxx:443] POST /gov/proposals {'content-type': 'text/plain', 'Digest': 'xxxxxxx', 'Authorization': 'Signature keyId=\"xxxxxx\",algorithm=\"hs2019\",headers=\"(request-target) digest content-length\",signature=\"xxxxxxx\"', 'content-length': '353231'} {\"script\": {\"text\": \"tables, args = ...;\\nreturn Calls:call(\\\"deploy_js_app\\\"xxxxxxx", args)\"}, \"parameter\": {\"bundle\": {\"metadata\": {\"e + 353103 chars\n"

Response from CCF:

_call_potentially_signed:84 - 500 {\"error\":{\"code\":\"InternalError\",\"message\":\"Proposal failed to bind to state.\"}}\n"

The proposal was retried.  Following is the request.

_call_potentially_signed:84 - [xxxxxx:443] POST /gov/proposals {'content-type': 'text/plain', 'Digest': xxxxxx', 'Authorization': 'Signature keyId=\"xxxxxx\",algorithm=\"hs2019\",headers=\"(request-target) digest content-length\",signature=\"xxxxx\"', 'content-length': '353231'} {\"script\": {\"text\": \"tables, args = ...;\\nreturn Calls:call(\\\"deploy_js_app\\\", args)\"}, \"parameter\": {\"bundle\": {\"metadata\": {\"e + 353103 chars\n"

Response from CCF:

_call_potentially_signed:84 - 415 {\"code\":\"UnsupportedContentType\",\"message\":\"Unsupported content type text/plain. Only application/json and application/msgpack are currently supported\"}}

In v0.16.3, the "UnsupportedContentType" error was observed the first time a proposal to deploy a JS application was sent. Upon retry, the proposal succeeded and the JS application was deployed. But in v0.18.1, the error is consistent and the JS application could not be deployed after multiple retries. 

CCF is deployed on a VM running Ubuntu Linux 18.04.

**Comment by letmaik** [comment] 2021-02-10 17:14
Regarding the second error, it seems like you're sending the wrong content type, which should be application/json.

**Comment by msftsettiy** [comment] 2021-02-10 19:34
I fixed the second error by setting the correct content type.  The first error still exists.  Up on retry, it worked. But, I am not blocked any more.

**Comment by achamayou** [comment] 2021-02-10 20:19
@msftsettiy the first issue may happen on a very early transaction coming in before the history has been set up on a node. A quick look at the code doesn’t turn up anything obvious, but we will investigate and fix the problem.

If you have additional context (is the request issued to the primary? a joiner? is it the first governance command?), it would be appreciated.

**Comment by achamayou** [comment] 2021-02-18 13:10
@msftsettiy could you confirm whether the node in question was running with multiple worker threads? Could you share the node's configuration please?

**Comment by lynshi** [comment] 2021-02-18 19:27
Just chiming in from our email thread.

We've also run into the "Proposal failed to bind state" error on CCF 0.18.1. I am working on reproducing, so I don't have answers to some of your questions yet - for example, we can't tell from the logs which node was hit since we connect to a Kubernetes Service which does the routing.

It is the first governance command, specifically `open_network()` after the member has made themselves active by acknowledging the state digest. I've also attached all the logs we have from node 0, which should be the primary. Nothing looks suspicious, though you can see the node's configuration in the first few lines.

{"h_ts":"2021-02-18T02:48:01.020475Z","thread_id":"100","level":"info","file":"../src/host/main.cpp","number":"439","msg":"Run with following options:\nversion=false\nenclave-file=\"/<REDACTED>/libtpal.enclave.so.signed\"\nenclave-type=0\nconsensus=0\nworker-threads=0\nnode-address=\"10.240.0.148:16384\"\nrpc-address=\"10.240.0.148:16385\"\npublic-rpc-address=\"10.240.0.148:16385\"\nledger-dir=\"/<REDACTED>/ledger\"\nread-only-ledger-dir=\"/<REDACTED>/read-only-ledger\"\nsnapshot-dir=\"/<REDACTED>/snapshots\"\nledger-chunk-bytes=104857600\nsnapshot-tx-interval=10000\nhost-log-level=2\nlog-format-json=true\nnode-cert-file=\"nodecert.pem\"\nnode-pid-file=\"cchost.pid\"\nsig-tx-interval=5000\nsig-ms-interval=1000\ncircuit-size-shift=22\nraft-timeout-ms=100\nraft-election-timeout-ms=5000\nbft-view-change-timeout-ms=5000\nbft-status-interval-ms=100\nmax-msg-size=24\nmax-fragment-size=16\ntick-period-ms=10\nsn=\"CN=CCF Node\"\nsan=\"dNSName:<REDACTED>.cloudapp.azure.com\" \"iPAddress:10.240.0.148\" \"dNSName:<REDACTED>\"\njwt-key-refresh-interval-s=1800\nmemory-reserve-startup=0\n[start]\nnetwork-cert-file=\"/<REDACTED>/networkcert.pem\"\ngov-script=\"/<REDACTED>/gov.lua\"\nmember-info=\"/<REDACTED>/public_key.pem,/<REDACTED>/keyshare.pem,/<REDACTED>/member_data.json\"\njoin.network-cert-file=\"networkcert.pem\"\njoin.join-timer=1000\nrecover.network-cert-file=\"networkcert.pem\"\n\n"}{"h_ts":"2021-02-18T02:48:01.022349Z","thread_id":"100","level":"info","file":"../src/host/main.cpp","number":"484","msg":"Recovery threshold unset. Defaulting to number of initial consortium members with a public encryption key (1).\n"}{"h_ts":"2021-02-18T02:48:01.849211Z","thread_id":"100","level":"info","file":"../src/host/ledger.h","number":"789","msg":"Recovered ledger entries up to 0, committed to 0\n"}{"h_ts":"2021-02-18T02:48:01.864953Z","thread_id":"100","level":"info","file":"../src/host/node_connections.h","number":"160","msg":"Listening for node-to-node on 10.240.0.148:16384\n"}{"h_ts":"2021-02-18T02:48:01.864982Z","thread_id":"100","level":"info","file":"../src/host/rpc_connections.h","number":"75","msg":"Listening for RPCs on 10.240.0.148:16385\n"}{"h_ts":"2021-02-18T02:48:01.865109Z","thread_id":"100","level":"info","file":"../src/host/main.cpp","number":"702","msg":"Creating new node: new network (with 1 initial member(s) and 1 member(s) required for recovery)\n"}Azure Quote Provider: libdcap_quoteprov.so [ERROR]: Could not retreive environment variable for 'AZDCAP_DEBUG_LOG_LEVEL'


For the secondary nodes, their logs end with the following
{"h_ts":"2021-02-18T02:49:18.919885Z","thread_id":"100","level":"info","file":"../src/host/ledger.h","number":"789","msg":"Recovered ledger entries up to 0, committed to 0\n"}{"h_ts":"2021-02-18T02:49:18.939507Z","thread_id":"100","level":"info","file":"../src/host/node_connections.h","number":"160","msg":"Listening for node-to-node on 10.240.0.174:16384\n"}{"h_ts":"2021-02-18T02:49:18.939537Z","thread_id":"100","level":"info","file":"../src/host/rpc_connections.h","number":"75","msg":"Listening for RPCs on 10.240.0.174:16385\n"}{"h_ts":"2021-02-18T02:49:18.939564Z","thread_id":"100","level":"info","file":"../src/host/main.cpp","number":"709","msg":"Creating new node - joining existing network at 10.240.0.148:16385\n"}{"h_ts":"2021-02-18T02:49:18.949020Z","thread_id":"100","level":"fail","file":"../src/host/main.cpp","number":"750","msg":"No snapshot found: Node will request all historical transactions\n"}Azure Quote Provider: libdcap_quoteprov.so [ERROR]: Could not retreive environment variable for 'AZDCAP_DEBUG_LOG_LEVEL'

These were printed 2-3 minutes before the "proposal failed to bind state" error, so I am assuming all the nodes have caught up with the history and can process transactions.

**Comment by achamayou** [comment] 2021-02-18 20:02
@lynshi thank you for the additional info, while #2207 does address a bug that could lead to the same symptoms, we still do not understand how this can occur with worker threads=0, nor are able to reproduce it in that configuration. We will continue to investigate, and cut a release tomorrow including this fix.

**Comment by settiy** [comment] 2021-02-18 21:24
Unfortunately, I do not have the logs any more as it has been overwritten. I will share the logs the next time I redeploy.

**Comment by achamayou** [comment] 2021-03-02 09:07
@settiy please re-open if you hit the UnsupportedContentType issue with either a valid or empty content type.

**Closed by achamayou** 2021-03-02 09:07 UTC
Labels: bug
