### ISSUE TITLE
Failure setting up RPC connection over docker network in virtual mode

### ISSUE THREAD

**Issue by ArvsIndrarys** [microsoft/CCF#615] opened 2019-12-06 15:47 UTC
**Describe the bug**

Launching the nodes inside the container produced by the VSCode Remote Container extension works. The next would have been for us to be able to deploy each node inside different containers.
But when launching them, the nodes that should join the started one fails to connect to it : 
```
uv_getaddrinfo failed: service not available for socket type
```

**To Reproduce**
Setup two nodes in docker containers, make the first start the network, transmit the network.cert to the second and make it join the started one.

**Expected behavior**
The second connected to the one and exchanging data.

**Environment information**
Using code available on master branch - via a container setup using the following Dockerfile :

```
FROM ubuntu:18.04

# set folder structure
WORKDIR /ccf_node
RUN mkdir -p enclave_files data/keypair consensus

# copy consensus types
COPY ./consensus/* consensus/
# copy examples applications
COPY ./enclave_files/* enclave_files/
# copy pre-generated binaries allowing us not to build at image creation ; it could be better but is far too long
COPY ./bin/* /usr/bin/
# copy node executable script
COPY ./launch_node.sh .

# install dependencies
RUN apt update && apt install -y software-properties-common git

RUN git clone https://github.com/microsoft/ccf
# override setup_no_driver with ours that adds a sudo presence check (no sudo inside a container -- should propose a merge request on it)
COPY ./setup_nodriver.sh /ccf_node/ccf/getting_started/setup_vm/setup_no_driver.sh
# run microsoft's ccf setup (dependencies, OpenEnclave, ....)
RUN /ccf_node/ccf/getting_started/setup_vm/setup_no_driver.sh

# set default environment vars
#global
ENV ENCLAVE_FILE libloggingenc.virtual.so
ENV ENCLAVE_TYPE virtual
ENV PROTOCOL_PORT 31555
ENV RPC_PORT 31550
ENV LOG_LEVEL info
ENV CONSENSUS_TYPE raft
ENV CONSENSUS_ELECTION_TIMEOUT_MS 100000
ENV NODE_NAME node

#start_network
ENV GOVERNANCE_FILE gov.lua
ENV NETWORK_CERT_FILE network.cert

RUN rm -r /ccf_node/ccf

# ensure the node will be always running
CMD [ "./launch_node.sh" ]
```

with the following structure: 
```
find build/
build/
build/Dockerfile
build/setup_nodriver.sh
build/enclave_files
build/enclave_files/libluagenericenc.virtual.so
build/enclave_files/libloggingenc.virtual.so
build/enclave_files/libsmallbankenc.virtual.so
build/launch_node.sh

--- The pre-generated binaries to avoid building them on each image creation (dev setup) ---
build/bin
build/bin/cchost.virtual
build/bin/keygenerator
build/bin/memberclient
build/consensus
build/consensus/gov.lua
build/consensus/operator_gov.lua
```

Version of the code being used, versions of dependencies, relevant environment info where applicable (OS, SGX driver...).

**Additional context**

* Log of one of the node trying to join the node that started the network *
```
ccf_node_1_1  | 2019-12-06T15:31:25.402629Z        [debug] ../src/ds/messaging.h:88             | Setting handler for OversizedMessage::fragment (4236346845)
ccf_node_1_1  | 2019-12-06T15:31:25.402827Z        [debug] ../src/ds/messaging.h:88             | Setting handler for AdminMessage::log_msg (1225314783)
ccf_node_1_1  | 2019-12-06T15:31:25.402835Z        [debug] ../src/ds/messaging.h:88             | Setting handler for AdminMessage::fatal_error_msg (1968599046)
ccf_node_1_1  | 2019-12-06T15:31:25.402842Z        [debug] ../src/ds/messaging.h:88             | Setting handler for AdminMessage::sealed_secrets (947406619)
ccf_node_1_1  | 2019-12-06T15:31:25.402940Z        [info ] ../src/host/main.cpp:361             | Creating new node - joining existing network at "ccf_node_0:31550"
ccf_node_1_1  | 2019-12-06T15:31:25.420985Z        [info ] ../src/host/main.cpp:383             | Created new node
ccf_node_1_1  | 2019-12-06T15:31:25.421878Z        [debug] ../src/ds/messaging.h:88             | Setting handler for consensus::ledger_append (3632665533)
ccf_node_1_1  | 2019-12-06T15:31:25.422414Z        [debug] ../src/ds/messaging.h:88             | Setting handler for consensus::ledger_truncate (121446211)
ccf_node_1_1  | 2019-12-06T15:31:25.422870Z        [debug] ../src/ds/messaging.h:88             | Setting handler for consensus::ledger_get (3870171435)
ccf_node_1_1  | 2019-12-06T15:31:25.423363Z        [debug] ../src/ds/messaging.h:88             | Setting handler for ccf::add_node (3687054425)
ccf_node_1_1  | 2019-12-06T15:31:25.423749Z        [debug] ../src/ds/messaging.h:88             | Setting handler for ccf::remove_node (2245805138)
ccf_node_1_1  | 2019-12-06T15:31:25.424146Z        [debug] ../src/ds/messaging.h:88             | Setting handler for ccf::node_outbound (3705027226)
ccf_node_1_1  | 2019-12-06T15:31:25.426461Z        [debug] ../src/ds/messaging.h:88             | Setting handler for AdminMessage::notification (3929878598)
ccf_node_1_1  | 2019-12-06T15:31:25.426942Z        [debug] ../src/ds/messaging.h:88             | Setting handler for tls::tls_outbound (382657439)
ccf_node_1_1  | 2019-12-06T15:31:25.427397Z        [debug] ../src/ds/messaging.h:88             | Setting handler for tls::tls_connect (4267421427)
ccf_node_1_1  | 2019-12-06T15:31:25.427899Z        [debug] ../src/ds/messaging.h:88             | Setting handler for tls::tls_stop (3542126935)
ccf_node_1_1  | 2019-12-06T15:31:25.428110Z        [debug] ../src/ds/messaging.h:88             | Setting handler for tls::tls_closed (2820057443)
ccf_node_1_1  | 2019-12-06T15:31:25.429049Z -0.026 [info ] ../src/node/nodestate.h:1115         | Node TLS connections now accepted
ccf_node_1_1  | 2019-12-06T15:31:25.429578Z        [debug] ../src/host/rpcconnections.h:218     | rpc connect request from enclave -9223372036854775808
ccf_node_1_1  | 2019-12-06T15:31:25.430652Z        [fail ] ../src/host/dns.h:59                 | uv_getaddrinfo failed: service not available for socket type
ccf_node_1_1  | 2019-12-06T15:31:25.431491Z        [debug] ../src/host/rpcconnections.h:207     | rpc write from enclave -9223372036854775808: 378
ccf_node_1_1  | 2019-12-06T15:31:25.431661Z        [fail ] ../src/host/rpcconnections.h:167     | Received an outbound message for id -9223372036854775808 which is not a known connection. Ignoring message of 378 bytes
ccf_node_1_1  | 2019-12-06T15:31:26.456857Z        [debug] ../src/host/rpcconnections.h:218     | rpc connect request from enclave -9223372036854775807
ccf_node_1_1  | 2019-12-06T15:31:26.457198Z        [fail ] ../src/host/dns.h:59                 | uv_getaddrinfo failed: service not available for socket type
ccf_node_1_1  | 2019-12-06T15:31:26.457269Z        [debug] ../src/host/rpcconnections.h:207     | rpc write from enclave -9223372036854775807: 378
ccf_node_1_1  | 2019-12-06T15:31:26.457285Z        [fail ] ../src/host/rpcconnections.h:167     | Received an outbound message for id -9223372036854775807 which is not a known connection. Ignoring message of 378 bytes
```

* Content of the modified setup_nodriver.sh *
```
#!/bin/bash
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache 2.0 License.

set -ex
if [ -x "$(sudo ls)" ];then
	sudo add-apt-repository ppa:ansible/ansible -y
	sudo apt-get update
	sudo apt install ansible -y
else
	apt update
	add-apt-repository ppa:ansible/ansible -y
	apt-get update
	apt install ansible -y
fi

ansible-playbook /ccf_node/ccf/getting_started/setup_vm/ccf-dependencies-no-driver.yml
```

Is there any support or interest helping on that error?
Is CCF ready only via IPC / local enclaves that prevent enclave recognition over a network?

**Comment by ArvsIndrarys** [comment] 2019-12-06 15:48
Or is the framework too young to be deployed in this case?

**Comment by achamayou** [comment] 2019-12-06 19:20
@ArvsIndrarys do you expose the ports or otherwise make the two containers able to talk to each other over the network?
Can you confirm that you can resolve adresses and establish successful TCP connections across your setup?

**Comment by ArvsIndrarys** [comment] 2019-12-06 20:40
@achamayou Yes, cUrl-ing works fine as I got the same results as in the VSCode container.
And I successfully am able to use the memberclient binary inside the container and on the host (not in any docker container).

**Comment by achamayou** [comment] 2019-12-07 09:32
Can you curl from one container to the next? Both ways? Can you share the details of how you configure the network and/or expose ports? Does the joining ip you pass to the second container resolve correctly to the first?

As long as the nodes can reach each other over the network, the service will be able to start.

**Comment by ArvsIndrarys** [comment] 2019-12-09 08:37
I am using docker-compose to create a network between each of the containers.
I can curl both ways, every node responds when I curl them with their docker-compose name, as the docker dns solves them right.

Example of a curl request :
```
root@7d7bcf3d1c62:/ccf_node# curl ccf_node_2:31550 -v
* Rebuilt URL to: ccf_node_2:31550/
*   Trying 172.19.0.3...
* TCP_NODELAY set
* Connected to ccf_node_2 (172.19.0.3) port 31550 (#0)
> GET / HTTP/1.1
> Host: ccf_node_2:31550
> User-Agent: curl/7.58.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host ccf_node_2 left intact
curl: (52) Empty reply from server
```


Content of the docker-compose.yml :
```
version: "3.7"

services:
  ccf_node_0:
    image: ccf_node:virtual-exp
    environment:
      - NODE_CMD=start
      - LOG_LEVEL=debug
    volumes:
      - ./data_node_0:/ccf_node/data

  ccf_node_1:
    image: ccf_node:virtual-exp
    environment:
      - NODE_CMD=join
      - TARGET_RPC_ADDRESS="ccf_node_0:31550"
      - LOG_LEVEL=debug
    volumes:
      - ./data_node_1:/ccf_node/data
      - ./data_node_0/network.cert:/ccf_node/data/network.cert
    depends_on:
      - ccf_node_0

  ccf_node_2:
    image: ccf_node:virtual-exp
    environment:
      - NODE_CMD=join
      - TARGET_RPC_ADDRESS="ccf_node_0:31550"
      - LOG_LEVEL=debug
    volumes:
      - ./data_node_2:/ccf_node/data
      - ./data_node_0/network.cert:/ccf_node/data/network.cert
    depends_on:
      - ccf_node_0
```
That type of configuration works with Ethereum parity, Hyperledger fabric, ... So I don't think the configuration is the cause.

`As long as the nodes can reach each other over the network, the service will be able to start.`
Yet it does not, that's why I declared it with the 'bug' label.

**Comment by ArvsIndrarys** [comment] 2019-12-09 09:37
I got the same error messages if the node that starts the network fails. Perhaps what I am trying to do does not work in virtual mode? Or do  have to link some IPC/whatever between them?

```
node_1_1  | 2019-12-09T09:31:55.689524Z        [debug] ../src/host/rpcconnections.h:218     | rpc connect request from enclave -9223372036854775806
node_1_1  | 2019-12-09T09:31:55.690121Z        [fail ] ../src/host/dns.h:59                 | uv_getaddrinfo failed: service not available for socket type
node_1_1  | 2019-12-09T09:31:55.690514Z        [debug] ../src/host/rpcconnections.h:207     | rpc write from enclave -9223372036854775806: 378
node_1_1  | 2019-12-09T09:31:55.690744Z        [fail ] ../src/host/rpcconnections.h:167     | Received an outbound message for id -9223372036854775806 which is not a known connection. Ignoring message of 378 bytes
node_2_1  | 2019-12-09T09:31:56.706542Z        [debug] ../src/host/rpcconnections.h:218     | rpc connect request from enclave -9223372036854775804
node_2_1  | 2019-12-09T09:31:56.706765Z        [fail ] ../src/host/dns.h:59                 | uv_getaddrinfo failed: service not available for socket type
node_2_1  | 2019-12-09T09:31:56.706801Z        [debug] ../src/host/rpcconnections.h:207     | rpc write from enclave -9223372036854775804: 378
node_2_1  | 2019-12-09T09:31:56.706826Z        [fail ] ../src/host/rpcconnections.h:167     | Received an outbound message for id -9223372036854775804 which is not a known connection. Ignoring message of 378 bytes
```
I think these messages imply that some kind of emulated enclave could not connect to others. Perhaps that in simulated mode, each `cchost.virtual` binary of each container generates some emulated enclave that are siloed?

**Comment by achamayou** [comment] 2019-12-09 11:28
@ArvsIndrarys thank you for providing additional detail, I think it's fairly clear that the dns resolution of "ccf_node_0" is failing on node_1 and node_2, although it's not clear to me why that is the case.
virtual/sgx should have no bearing on this at all, all networking is handled by libuv on the host, regardless of how the enclave is run. There is no need for special IPC, the nodes communicate over regular tcp sockets.

Let us have a closer look at the repro and get back to you.

**Comment by ArvsIndrarys** [comment] 2019-12-09 12:58
I can give a zip containing all my files if you need it.
It is surely not production-grade but I can launch everything with a single command, so it could help.

**Comment by olgavrou** [comment] 2019-12-09 17:46
Hello @ArvsIndrarys 

Can you please try to remove the quotes around `-TARGET_RPC_ADDRESS="ccf_node_0:31550"` in your docker compose file? So make it: `- TARGET_RPC_ADDRESS=ccf_node_0:31550` and let me know how that goes?

We managed to reproduce the same issue as you are describing above and then resolved it by removing the quotes around the target rpc address.

We will add some extra logging on our side to hopefully make something like this more clear in the future.

Thank you,
Olga

**Comment by ArvsIndrarys** [comment] 2019-12-10 10:04
Still does not work for me.
I am considering the fact that it is due to my host being on Ubuntu16 and 18. I rebuilt everything from  today's master branch , so I don't think it is caused by a difference in the binaries. 
Can you confirm the OS you tried on?

**Comment by olgavrou** [comment] 2019-12-10 12:49
Hi @ArvsIndrarys 

If it helps I am running on Ubuntu 18.04 with docker version: 19.03.5 and docker-compose version: 1.25.0

Please see my setup below. I have managed to make the nodes communicate effectively. The next thing that is possibly happening is that you need to set the `--domain` cli argument when launching the nodes so that it can be known what DNS is to be used for TLS certificate validation.

docker-compose.yml

```
version: "3.7"

services:
  ccfnode0.test:
    image: ccfciteam/ccf-ci-18.04
    environment:
      - NODE_CMD=start
      - PROTOCOL_PORT=31555
      - RPC_PORT=31550
      - HOSTNAME=ccfnode0.test
    command: ./launch_node.sh 0 &
    volumes:
      - ./launch_node.sh:/launch_node.sh
      - ./build:/ccf_build
  ccfnode1.test:
    image: ccfciteam/ccf-ci-18.04
    environment:
      - NODE_CMD=join
      - TARGET_RPC_ADDRESS=ccfnode0.test:31550
      - PROTOCOL_PORT=31556
      - RPC_PORT=31557
      - HOSTNAME=ccfnode1.test
    command: ./launch_node.sh 1 &
    volumes:
      - ./join_node.sh:/launch_node.sh
      - ./build:/ccf_build
    depends_on:
      - ccfnode0.test
```

launch_node.sh script

```
#!/bin/bash

node=$1
cd /ccf_build

rm -rf workspace/logging_$node
mkdir -p workspace/logging_$node
ln -sf /ccf_build/cchost.virtual workspace/logging_$node/cchost.virtual
ln -sf /ccf_build/libsmallbankenc.virtual.so workspace/logging_$node/libsmallbankenc.virtual.so

cp /ccf_build/member* workspace/logging_$node/
cp /ccf_build/gov.lua workspace/logging_$node/gov.lua
cd workspace/logging_$node

./cchost.virtual --enclave-file=./libsmallbankenc.virtual.so --enclave-type=virtual --node-address=$HOSTNAME:$PROTOCOL_PORT --rpc-address=$HOSTNAME:$RPC_PORT --public-rpc-address=$HOSTNAME:$RPC_PORT --ledger-file=$node.ledger --node-cert-file=$node.pem --host-log-level=debug --raft-election-timeout-ms=100000 --consensus=raft --quote-file=quote$node.bin --domain=test $NODE_CMD --network-cert-file=/ccf_build/workspace/logging_0/networkcert.pem --gov-script=gov.lua --member-cert=member0_cert.pem --member-cert=member1_cert.pem --member-cert=member2_cert.pem 1>/ccf_build/workspace/logging_$node/out 2>/ccf_build/workspace/logging_$node/err

```

join_node.sh script

```
#!/bin/bash

node=$1
cd /ccf_build

rm -rf workspace/logging_$node
mkdir -p workspace/logging_$node
ln -sf /ccf_build/cchost.virtual workspace/logging_$node/cchost.virtual
ln -sf /ccf_build/libsmallbankenc.virtual.so workspace/logging_$node/libsmallbankenc.virtual.so

cp /ccf_build/member* workspace/logging_$node/
cp /ccf_build/gov.lua workspace/logging_$node/gov.lua
cd workspace/logging_$node

./cchost.virtual --enclave-file=./libsmallbankenc.virtual.so --enclave-type=virtual --node-address=$HOSTNAME:$PROTOCOL_PORT --rpc-address=$HOSTNAME:$RPC_PORT --public-rpc-address=$HOSTNAME:$RPC_PORT --ledger-file=$node.ledger --node-cert-file=$node.pem --host-log-level=debug --raft-election-timeout-ms=100000 --consensus=raft --quote-file=quote$node.bin --domain=test $NODE_CMD --network-cert-file=/ccf_build/workspace/logging_0/networkcert.pem --target-rpc-address=$TARGET_RPC_ADDRESS 1>/ccf_build/workspace/logging_$node/out 2>/ccf_build/workspace/logging_$node/err

```

I have checked out and built CCF. I have placed the docker compose and bash scripts under the CCF directory (which will have `build` as a subdirectory). I am mounting `build` on both of the containers and moving files around accordingly. I am also using the CCF docker image that has the dependencies needed.

The directory structure looks like this and I am running docker compose from inside `CCF`

```
.
└── CCF
   [...]
    ├── build
    ├── docker-compose.yml
    ├── join_node.sh
    ├── launch_node.sh
    ├── src
  [...]
```

You could either mirror the above setup or adjust yours accordingly and let us know how it goes. On our side we will look into updating the documentation if needed to make things more clear.

Thanks,
Olga

**Comment by ArvsIndrarys** [comment] 2019-12-10 13:40
Hi Olga, your setup works for me ; I did not know about the `ccfciteam/ccf-ci-18.04` image.

Thanks for helping us!

**Comment by olgavrou** [comment] 2019-12-10 13:45
Glad to hear it!

I'll close it :)

**Closed by olgavrou** 2019-12-10 13:45 UTC
Labels: bug
