### ISSUE TITLE
Expose an endpoint to retrieve the current constitution

### ISSUE THREAD

**Issue by lynshi** [microsoft/CCF#4170] opened 2022-08-24 20:54 UTC
The addition of an endpoint to get the constitution, such as `GET /gov/constitution`, would be helpful for members and users to understand more about the CCF network. Similar to the existing `/gov/members`, this would provide a convenient way for entities to retrieve public information about the network's governance.

I checked the current schemas for `/node` and `/gov` and didn't seem to find anything related.

**Comment by eddyashton** [comment] 2022-08-25 12:41
@lynshi We are planning to support this with a more generic mechanism to access _all_ governance tables - #4073. Is that sufficient?

**Comment by lynshi** [comment] 2022-08-25 15:01
Sorry, I didn't see that, that's perfect - thanks!

**Comment by eddyashton** [comment] 2022-08-25 15:49
Closing as duplicate of #4073.

**Closed by eddyashton** 2022-08-25 15:49 UTC
Labels: enhancement
