### ISSUE TITLE
The multiple inflight proposal check for BFT after reconfiguration appears to be broken

### ISSUE THREAD

**Issue by ashamis** [microsoft/CCF#2668] opened 2021-06-15 14:09 UTC
Need to investigate to come-up with a proper solution

For reference, the original change was introduced as part of https://github.com/microsoft/CCF/pull/2350

**Comment by achamayou** [comment] 2021-06-17 09:37
Duplicate of #2136, adding a nonce to duplicate proposals such as transition network to open is a short term workaround until we decide what solution we want.

**Closed by achamayou** 2021-06-17 09:37 UTC
Labels: bug
