### ISSUE TITLE
Replace `buffer.h` with `std::span`

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#3567] opened 2022-02-17 16:26 UTC
We used to have an owning variant of these buffers, but that's been replaced throughout with other types. The remaining `CBuffer` type is unnecessary, and could be replaced with `std::span` throughout.

**Comment by achamayou** [comment] 2022-02-17 18:01
dupe of #1198?

**Closed** 2022-02-17 18:04 UTC
Labels: TODO
