### ISSUE TITLE
Implement `remove` for RBMap

### ISSUE THREAD

**Issue by jeffa5** [microsoft/CCF#4789] opened 2022-12-22 11:45 UTC
**Is your feature request related to a problem? Please describe.**

Currently the RBMap can't be used for typical builds since it doesn't implement `remove` (currently it gives a runtime error). It would be useful to have this map enabled for the more efficient range operations it provides.

**Describe the solution you'd like**

The `rb::Map::remove` function to be implemented.

**Describe alternatives you've considered**

Using the CHAMP map, but the range performance isn't suitable for heavy use-cases.

**Additional context**

#4788

**Comment by jumaffre** [comment] 2022-12-22 14:28
Duplicate of https://github.com/microsoft/CCF/issues/4146 so I'll close this.

**Closed by jumaffre** 2022-12-22 14:28 UTC
Labels: enhancement
