### ISSUE TITLE
Allow `remove_node` proposal to remove nodes that are waiting for `transition_node_to_trusted` proposal.

### ISSUE THREAD

**Issue by gaurav137** [microsoft/CCF#6463] opened 2024-09-04 16:34 UTC
When orchestrating CCF cluster creations we'd want to be able to cleanup failed node creation attempts where a node was started in join mode but a `transition_node_to_trusted` proposal for it was never submitted/accepted. Currently `remove_node` looks like a no-op for nodes in such a state. Being able to remove such pending nodes via `remove_node` will be desirable.

**Comment by achamayou** [comment] 2024-09-04 16:37
@gaurav137 proposals in the sample constitution are generally idempotent (see full discussion at #2169), and so `remove_*` is always a no-op if the item is not there. Adding the ability to `remove_node` pending nodes should be quite straightforward.

**Comment by achamayou** [comment] 2024-09-11 12:54
@gaurav137 could you confirm what you mean by "looks like a no-op"?

The default constitution does allow removing "Pending" nodes, and specifically deletes them at once, without going through retirement: https://github.com/microsoft/CCF/blob/main/samples/constitutions/default/actions.js#L1276

This is tested by https://github.com/microsoft/CCF/blob/main/tests/reconfiguration.py#L399

**Comment by gaurav137** [comment] 2024-09-12 04:22
Here is what I see.

New node starts waiting to get trusted:
```sh
[info ] ../src/node/node_state.h:744         | Node n[0037f5d6561f865f55f9993cd625e33a3c6da73685d83ac9c8c495343a198f04] is waiting for votes of members to be trusted
2024-09-12T04:13:14.194505Z        100 [info ] ../src/host/socket.h:53              | TCP RPC Client connected
2024-09-12T04:13:14.304188Z -0.001 0   [info ] ../src/node/node_state.h:744         | Node n[0037f5d6561f865f55f9993cd625e33a3c6da73685d83ac9c8c495343a198f04] is waiting for votes of members to be trusted
2024-09-12T04:13:15.195438Z        100 [info ] ../src/host/socket.h:53              | TCP RPC Client connected
2024-09-12T04:13:15.308098Z -0.002 0   [info ] ../src/node/node_state.h:744         | Node n[0037f5d6561f865f55f9993cd625e33a3c6da73685d83ac9c8c495343a198f04] is waiting for votes of members to be trusted
```

Then raise a `remove_node` proposal instead of trusting the node. The primary node logs the below message:
```
2024-09-12T04:14:02.475839Z -0.015 0   [info ][gov] /gov/gov_endpoint_registry.h:58 | RequestCompletedEvent: POST /members/proposals:create 200 14ms 1 attempt(s)
2024-09-12T04:14:02.479160Z -0.005 0   [info ][gov] /gov/gov_endpoint_registry.h:58 | RequestCompletedEvent: GET /tx 200 0ms 1 attempt(s)
2024-09-12T04:14:02.940660Z -0.002 0   [info ] ../src/node/quote.cpp:203            | Skipped attestation report verification
2024-09-12T04:14:02.940736Z -0.002 0   [info ] ../src/node/rpc/node_frontend.h:339  | Node n[0037f5d6561f865f55f9993cd625e33a3c6da73685d83ac9c8c495343a198f04] added as PENDING
2024-09-12T04:14:02.999984Z -0.001 0   [info ][gov] /gov/gov_endpoint_registry.h:58 | RequestCompletedEvent: GET /tx 200 0ms 1 attempt(s)
```

Our tracking logic does not see this node moving from `Pending` to `Retired` in the `/node/network/nodes` output.
```sh
info: Controllers.NetworksController[0]
      Waiting for https://host.docker.internal:61724/node/network/nodes to list 0037f5d6561f865f55f9993cd625e33a3c6da73685d83ac9c8c495343a198f04 with status Retired in its output.
```

Rather `/node/network/nodes` output remains as below:
```sh
> curl -k -s https://localhost:61724/node/network/nodes | jq
{
  "nodes": [
    {
      "last_written": 1,
      "node_data": {
        "id": "testnet-virtual-0",
        "infraProviderData": null,
        "name": "testnet-virtual-0"
      },
      "node_id": "1156aef723f53fa522f41141fd44791f3a0c38aa2f1337a2412ed778dc1ce30e",
      "primary": true,
      "rpc_interfaces": {
        "debug_interface": {
          "bind_address": "0.0.0.0:8082",
          "endorsement": {
            "authority": "Node"
          },
          "published_address": "testnet-virtual-0:8082"
        },
        "primary_rpc_interface": {
          "bind_address": "0.0.0.0:8080",
          "published_address": "testnet-virtual-0:8080"
        }
      },
      "status": "Trusted"
    },
    {
      "last_written": 14,
      "node_data": {
        "id": "testnet-virtual-1",
        "infraProviderData": null,
        "name": "testnet-virtual-1"
      },
      "node_id": "0037f5d6561f865f55f9993cd625e33a3c6da73685d83ac9c8c495343a198f04",
      "primary": false,
      "rpc_interfaces": {
        "debug_interface": {
          "bind_address": "0.0.0.0:8082",
          "endorsement": {
            "authority": "Node"
          },
          "published_address": "testnet-virtual-1:8082"
        },
        "primary_rpc_interface": {
          "bind_address": "0.0.0.0:8080",
          "published_address": "testnet-virtual-1:8080"
        }
      },
      "status": "Pending"
    }
  ]
}
```

**Comment by achamayou** [comment] 2024-09-12 09:40
@gaurav137 I see you create the proposal, but it's not obvious that it's accepted. Assuming it is though, the node will get deleted in the KV, not set to `Retired`, as per: https://github.com/microsoft/CCF/blob/main/samples/constitutions/default/actions.js#L1276

This is because the retirement protocol is unnecessary for such nodes, as they never joined a configuration.

If the node in question is still running however, it will continue to send join requests, and get back to a `Pending` state, which is why I think you continue to see it. You ought to be able to confirm that's the case by observing that the `"last_written"` value goes up soon after you propose and pass a `remove_node` succesfully.

My suggestion is that if you do not intend to trust a node, you shut it down first, and propose its removal afterwards. That will prevent it becoming Pending again.

The other alternatives I can think of are:

1. Keep track of nodes that have been deleted, to avoid them re-joining. This is obviously undesirable, at it leads to potentially unbounded state growth.
2. Change the join protocol, which is currently a single command, to a multi-step sequence. Add a new message that allows nodes that have confirmed their pending status is committed to poll for trust without creating a new entry if there isn't one. That's a non-trivial change that would need to be made backwards compatible, just to support leaving nodes running after they have been removed.

In the interest of keeping things simple, I think shutting down the node before removing it is best.

**Closed** 2024-10-08 14:22 UTC
Labels: enhancement
