### ISSUE TITLE
JWT token validation fails

### ISSUE THREAD

**Issue by msftsettiy** [microsoft/CCF#1549] opened 2020-08-28 17:14 UTC
**Describe the bug**
I created a Javascript (JS) method to verify a JSON Web token(JWT). The method uses jsrsasign.VerifyJWT() method. The verification failed (VerifyJWT method returned false) when run in CCF using the libjs_generic package in virtual enclave mode. The same method worked fine when run in the Firefox browser. I verified the token at jwt.io and https://kjur.github.io/jsrsasign/tool/tool_jwtveri.html and both of them returned true for the same set of parameters as passed in the JS method. 

**To Reproduce**
I used the following JS method to verify a JWT.
***********************************************
// import the library
import * as rs  from 'jsrsasign'; // version 8.0.22

// function to verify a JWT
export function verifytoken() {
    let publickey = "-----BEGIN PUBLIC KEY-----MIG...-----END PUBLIC KEY-----";
    let body = "eyJhbGciOiAiU...";
    try {
        return rs.KJUR.jws.JWS.verifyJWT(body, publickey,{alg: ['RS256'], verifyAt: rs.KJUR.jws.IntDate.get('1598374054')}); // must return true
    }catch (e) {
        return e.message;
      }
}
***********************************************

**Expected behavior**
The verifytoken() method should return true.

**Environment information**
CCF: master branch
Package: libjs_generic
OS: Linux xxx-18 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
jsrsasign: "^8.0.22"

**Additional context**

**Comment by letmaik** [comment] 2020-09-01 14:22
I could reproduce this. In fact, it worked if you hard-code the body inside the endpoint function, which means there is an issue with passing the body from the request to the endpoint.
Doing a `console.log(body)` inside the endpoint shows:
```
2020-09-01T14:13:55.125412Z -3.781 0   [info ] rc/apps/js_generic/js_generic.cpp:43 | "eyJhbGciOiAiUlMyNTYiLCA...
```
The body is always converted to JSON and (at least for now) must be parsed before using it:
`let token = JSON.parse(body)`.
I agree though that this is very counterintuitive. I would have expected either the original body or the parsed body as JS object, but not the parsed body re-encoded as a JSON string.

I think this may have to do with the Lua roundtrip and will probably be done a bit differently after that's gone, especially once APIs can be described in a descriptive manner, including the request and response media types.

@eddyashton

**Comment by letmaik** [comment] 2020-09-01 14:40
@msftsettiy I just noticed that in your example you did also hard-code the body in the endpoint function. Are you sure this variant failed? It works for me. But anyway, if you get the token via the body, then you need to `JSON.parse` it first.

**Comment by achamayou** [comment] 2020-09-01 14:44
@letmaik there is no Lua roundtrip, and the body isn't particularly converted to anything, it is passed as a raw string to the javascript: https://github.com/microsoft/CCF/blob/master/src/apps/js_generic/js_generic.cpp#L355

The string is deliberately not parsed as JSON, because it may not be and endpoints may want to deal with content types other than json.

**Comment by achamayou** [comment] 2020-09-01 14:45
It probably would be nicer to expose this as another type, perhaps https://developer.mozilla.org/en-US/docs/Web/API/Blob, and that's definitely something we should give more thought to.

**Comment by letmaik** [comment] 2020-09-01 15:23
Hm, well someone is adding quotes around the string. Maybe that's just an issue of the test framework?

**Comment by msftsettiy** [comment] 2020-09-01 15:31
@letmaik, the validation succeeded with JSON.parse(body) in the JS method.

**Comment by achamayou** [comment] 2020-09-01 15:59
@letmaik that's the implementation of console.log: https://github.com/microsoft/CCF/blob/master/src/apps/js_generic/js_generic.cpp#L37

**Comment by letmaik** [comment] 2020-09-01 16:46
@msftsettiy The problem here is that the test framework tried to be helpful and converts all payloads in a `.post()` call to JSON. That's why parsing is necessary on the other end. It would probably be useful if the framework would support some kind of raw mode as well.

**Comment by letmaik** [comment] 2020-09-01 16:48
I'll close this issue and will open a new one for raw data since that should be tested as well.

**Closed by letmaik** 2020-09-01 16:48 UTC
Labels: bug
