### ISSUE TITLE
code_update_test fails on CI

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#2378] opened 2021-03-30 10:54 UTC
We have occasional failures in the `code_update_test` during CI runs, which I believe has started recently:

https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=22126&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=efdbc34d-c6b6-5dc6-e05c-1751d4c47c20&l=16704
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=22138&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=efdbc34d-c6b6-5dc6-e05c-1751d4c47c20&l=16789

Both of these are in SGX Debug. The latter has a segfault node crash, while the former doesn't. Both appear to have a failure to establish a node-to-node channel:

```
62: 10:15:33.702 | ERROR    | infra.remote:log_errors:70 - /mnt/build/1/s/build/workspace/code_update_test_2/out: 2021-03-30T10:15:26.927312Z -0.001 0   [fail ] ../src/node/channels.h:781           | Node channel with 22176ee69ffcc7b157e9ef4b154b0235e04f47f61205b5cb6471692489e0b61f cannot receive authenticated message: not yet established, status=0
62: 10:15:33.702 | ERROR    | infra.remote:log_errors:70 - /mnt/build/1/s/build/workspace/code_update_test_2/out: 2021-03-30T10:15:26.927339Z -0.001 0   [fail ] ../src/consensus/aft/raft.h:679      | Exception in void aft::Aft<consensus::LedgerEnclave, ccf::NodeToNode, ccf::Snapshotter>::recv_message(const ccf::NodeId &, OArray &&) [LedgerProxy = consensus::LedgerEnclave, ChannelProxy = ccf::NodeToNode, SnapshotterProxy = ccf::Snapshotter]
62: 10:15:33.702 | ERROR    | infra.remote:log_errors:70 - /mnt/build/1/s/build/workspace/code_update_test_2/out: 2021-03-30T10:15:27.729962Z -0.001 0   [fail ] ../src/node/channels.h:781           | Node channel with 8c52ba6383d40b50af43c38c87f85d79a754a5af694da0a056bf53a15acfd115 cannot receive authenticated message: not yet established, status=0
62: 10:15:33.702 | ERROR    | infra.remote:log_errors:70 - /mnt/build/1/s/build/workspace/code_update_test_2/out: 2021-03-30T10:15:27.730003Z -0.001 0   [fail ] ../src/consensus/aft/raft.h:679      | Exception in void aft::Aft<consensus::LedgerEnclave, ccf::NodeToNode, ccf::Snapshotter>::recv_message(const ccf::NodeId &, OArray &&) [LedgerProxy = consensus::LedgerEnclave, ChannelProxy = ccf::NodeToNode, SnapshotterProxy = ccf::Snapshotter]
62: 10:15:33.702 | ERROR    | infra.remote:log_errors:70 - /mnt/build/1/s/build/workspace/code_update_test_2/out: 2021-03-30T10:15:29.288830Z -0.001 0   [fail ] ../src/node/channels.h:781           | Node channel with d2039e880d33f89fea67a3e3c59a8470ccf5aa116e3ec6f2cb7ba5c102391207 cannot receive authenticated message: not yet established, status=0
62: 10:15:33.702 | ERROR    | infra.remote:log_errors:70 - /mnt/build/1/s/build/workspace/code_update_test_2/out: 2021-03-30T10:15:29.288864Z -0.001 0   [fail ] ../src/consensus/aft/raft.h:679      | Exception in void aft::Aft<consensus::LedgerEnclave, ccf::NodeToNode, ccf::Snapshotter>::recv_message(const ccf::NodeId &, OArray &&) [LedgerProxy = consensus::LedgerEnclave, ChannelProxy = ccf::NodeToNode, SnapshotterProxy = ccf::Snapshotter]
62: 10:15:33.702 | ERROR    | infra.remote:log_errors:70 - /mnt/build/1/s/build/workspace/code_update_test_2/out: 2021-03-30T10:15:31.305218Z -0.002 0   [fail ] ../src/node/channels.h:781           | Node channel with 8c52ba6383d40b50af43c38c87f85d79a754a5af694da0a056bf53a15acfd115 cannot receive authenticated message: not yet established, status=0
62: 10:15:33.702 | ERROR    | infra.remote:log_errors:70 - /mnt/build/1/s/build/workspace/code_update_test_2/out: 2021-03-30T10:15:31.305244Z -0.002 0   [fail ] ../src/consensus/aft/raft.h:679      | Exception in void aft::Aft<consensus::LedgerEnclave, ccf::NodeToNode, ccf::Snapshotter>::recv_message(const ccf::NodeId &, OArray &&) [LedgerProxy = consensus::LedgerEnclave, ChannelProxy = ccf::NodeToNode, SnapshotterProxy = ccf::Snapshotter]
62: 10:15:33.702 | ERROR    | infra.remote:log_errors:70 - /mnt/build/1/s/build/workspace/code_update_test_2/out: 2021-03-30T10:15:32.015973Z -0.001 0   [fail ] ../src/node/channels.h:781           | Node channel with 22176ee69ffcc7b157e9ef4b154b0235e04f47f61205b5cb6471692489e0b61f cannot receive authenticated message: not yet established, status=0
```

**Comment by achamayou** [comment] 2021-03-30 12:11
@wintersteiger could you have a look please?

**Comment by wintersteiger** [comment] 2021-03-30 12:18
Sure!

**Comment by wintersteiger** [comment] 2021-03-31 09:16
There is at least one bug in the channels implementation, working on it.

Just so I don't forget: For this type of trace: 

```
Stack trace (most recent call last) in thread 596:
#31   Object "/usr/lib/x86_64-linux-gnu/libsgx_urts.so", at 0x7ff8e98236d2, in
#30   Object "./cchost", at 0xf73da8, in
#29   Object "./cchost", at 0x531efa, in
#28   Object "./cchost", at 0x7f00af, in
#27   Object "./cchost", at 0x7f0612, in
#26   Object "./cchost", at 0x7f0da7, in
#25   Object "./cchost", at 0x7f80d0, in
#24   Object "./cchost", at 0x7f8338, in
#23   Object "/lib/x86_64-linux-gnu/libgcc_s.so.1", at 0x7ff8ec7dd097, in _Unwind_Backtrace
#22   Object "/lib/x86_64-linux-gnu/libgcc_s.so.1", at 0x7ff8ec7db53f, in
#21   Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7ff8ecf9c97f, in
#20   Object "/usr/lib/x86_64-linux-gnu/libsgx_urts.so", at 0x7ff8e98236d2, in
```

I was able to get a readable stack trace like so:

```
...$ addr2line -fC -e cchost 0xf73da8 0x531efa 0x7f00af 0x7f0612 0x7f0da7 0x7f80d0 0x7f8338
_host_signal_handler
/data/cwinter/openenclave/build/../host/sgx/linux/exception.c:72
stacktrace::sig_handler(int, siginfo_t*, void*)
/data/cwinter/CCF/build/../src/ds/stacktrace_utils.h:52
backward::SignalHandling::handleSignal(int, siginfo_t*, void*)
/data/cwinter/CCF/build/../3rdparty/exported/backward-cpp/backward.hpp:3947
backward::StackTraceImpl<backward::system_tag::linux_tag>::load_from(void*, unsigned long)
/data/cwinter/CCF/build/../3rdparty/exported/backward-cpp/backward.hpp:823
backward::StackTraceImpl<backward::system_tag::linux_tag>::load_here(unsigned long)
/data/cwinter/CCF/build/../3rdparty/exported/backward-cpp/backward.hpp:817
unsigned long backward::details::unwind<backward::StackTraceImpl<backward::system_tag::linux_tag>::callback>(backward::StackTraceImpl<backward::system_tag::linux_tag>::callback, unsigned long)
/data/cwinter/CCF/build/../3rdparty/exported/backward-cpp/backward.hpp:802
backward::details::Unwinder<backward::StackTraceImpl<backward::system_tag::linux_tag>::callback>::operator()(backward::StackTraceImpl<backward::system_tag::linux_tag>::callback&, unsigned long)
/data/cwinter/CCF/build/../3rdparty/exported/backward-cpp/backward.hpp:759
```

That's without LVI mitigations and the `cchost` binary that produced it. This was a segfault, but I'm not sure whether that was the root cause for this trace; could be an uncaught exception during signal handling too.

**Comment by eddyashton** [comment] 2021-03-31 09:33
@wintersteiger That looks like a recursive stacktrace in `backward-cpp`, the library which is supposed to be producing the stacktrace. We've seen this previously when we had out-of-memory errors and I believe also with stack corruption - the library segfaults while producing a stacktrace, and the segfault handler tries to produce a stacktrace. Repeat ad infinitum. So probably not the root cause.

**Comment by achamayou** [comment] 2021-03-31 09:37
Should we reconsider our use of backward-cpp then?

**Comment by wintersteiger** [comment] 2021-03-31 10:31
Thanks @eddyashton, I agree, that's exactly what it looks like! 

@achamayou it might be an easy fix - did anybody ever look into whether it would take just an `if (x != nullptr) ...` in backward-cpp to cut off the recursion?

**Comment by eddyashton** [comment] 2021-03-31 10:45
I had an attempted fix for this in #1590, which was to install and remove the signal handler ourselves rather than using the installer provided by backward-cpp. I'm sure this fixed _a_ repro at the time, but it now looks like that wasn't a general fix. Glancing at the code, I wonder if I was being stupid in `stackrace_utils.h`:

```
  static void sig_handler(int signo, siginfo_t* info, void* _ctx)
  {
    backward::SignalHandling::handleSignal(signo, info, _ctx);
    LOG_FATAL_FMT("Handled fatal signal {}", signo);

    // SA_RESETHAND seems to be insufficient, so we manually reset the handler
    // before re-raising
    signal(signo, SIG_DFL);
    raise(signo);
  }
```

We should probably be resetting the handler _before_ calling `backward::handleSignal()`, in case _it_ raises the same signal? But this doesn't help us find the root cause.

**Comment by wintersteiger** [comment] 2021-03-31 10:54
Yeah, that looks wrong to me too. This is super hard and time-consuming to debug. Maybe we could contrive a test that tries to throw random assertions and signals to make sure we catch everything?

**Comment by achamayou** [comment] 2021-03-31 12:12
If backwards-cpp truly gives us something material, then maybe it's worth looking into it, otherwise I think it'd tempting to file under "not worth it, the default handler is good enough mostly, load the core in a debugger if/when you need more details".

**Comment by wintersteiger** [comment] 2021-03-31 12:50
I still don't understand why it doesn't resolve those symbols. Does it never resolve them or were there simply no recent bugs with nice traces for me to see?

**Comment by eddyashton** [comment] 2021-04-01 09:54
We have another repro of the election timeout in the Daily: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=22498&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=63d660c3-6f76-573a-0154-fd0bcb096ded&l=15999

The error lines about the channel exceptions are a red herring - those are only printed on a node after it has retired itself. We should try to log that less aggressively, since the node should know its not truly an error, but that's not the problem here.

We appear to be stuck in a classic election cycle, where one of the nodes is unable to communicate with another node that it needs to pass an election. In particular, we are continually re-creating node-to-node channels.

##### Node 4 can't talk to node 3 or 5
```
2021-04-01T07:25:59.834739Z -0.001 0   [info ] ../src/consensus/aft/raft.h:2307     | Becoming candidate [NODE 4]: 5
2021-04-01T07:25:59.834832Z -0.001 0   [info ] ../src/consensus/aft/raft.h:2112     | Send request vote from [NODE 4] to [NODE 5] at 77
2021-04-01T07:25:59.834838Z -0.001 0   [info ] ../src/node/channels.h:709           | Initiating node channel with [NODE 5].
2021-04-01T07:25:59.835972Z -0.003 0   [info ] ../src/consensus/aft/raft.h:2112     | Send request vote from [NODE 4] to [NODE 2] at 77
2021-04-01T07:25:59.836005Z -0.003 0   [info ] ../src/consensus/aft/raft.h:2112     | Send request vote from [NODE 4] to [NODE 3] at 77
2021-04-01T07:25:59.836011Z -0.003 0   [info ] ../src/node/channels.h:709           | Initiating node channel with [NODE 3].
2021-04-01T07:26:02.009285Z -0.001 0   [info ] ../src/consensus/aft/raft.h:2307     | Becoming candidate [NODE 4]: 6
2021-04-01T07:26:02.009306Z -0.001 0   [info ] ../src/consensus/aft/raft.h:2112     | Send request vote from [NODE 4] to [NODE 5] at 77
2021-04-01T07:26:02.009309Z -0.001 0   [info ] ../src/node/channels.h:709           | Initiating node channel with [NODE 5].
2021-04-01T07:26:02.010453Z -0.002 0   [info ] ../src/consensus/aft/raft.h:2112     | Send request vote from [NODE 4] to [NODE 2] at 77
2021-04-01T07:26:02.010525Z -0.002 0   [info ] ../src/consensus/aft/raft.h:2112     | Send request vote from [NODE 4] to [NODE 3] at 77
2021-04-01T07:26:02.010531Z -0.002 0   [info ] ../src/node/channels.h:709           | Initiating node channel with [NODE 3].
```

#### Node 5 only gets responses from node 3
```
2021-04-01T07:26:01.893463Z -0.001 0   [info ] ../src/consensus/aft/raft.h:2307     | Becoming candidate [NODE 5]: 6
2021-04-01T07:26:01.893519Z -0.001 0   [info ] ../src/consensus/aft/raft.h:2112     | Send request vote from [NODE 5] to [NODE 2] at 77
2021-04-01T07:26:01.893556Z -0.001 0   [info ] ../src/consensus/aft/raft.h:2112     | Send request vote from [NODE 5] to [NODE 4] at 77
2021-04-01T07:26:01.893587Z -0.001 0   [info ] ../src/consensus/aft/raft.h:2112     | Send request vote from [NODE 5] to [NODE 3] at 77
2021-04-01T07:26:01.951334Z -0.001 0   [info ] ../src/consensus/aft/raft.h:2283     | Recv request vote response to [NODE 5] from [NODE 3]: they voted yes
2021-04-01T07:26:05.028651Z -0.001 0   [info ] ../src/consensus/aft/raft.h:2307     | Becoming candidate [NODE 5]: 7
2021-04-01T07:26:05.028666Z -0.001 0   [info ] ../src/consensus/aft/raft.h:2112     | Send request vote from [NODE 5] to [NODE 2] at 77
2021-04-01T07:26:05.028695Z -0.001 0   [info ] ../src/consensus/aft/raft.h:2112     | Send request vote from [NODE 5] to [NODE 4] at 77
2021-04-01T07:26:05.028700Z -0.001 0   [info ] ../src/consensus/aft/raft.h:2112     | Send request vote from [NODE 5] to [NODE 3] at 77
2021-04-01T07:26:05.031024Z -0.004 0   [info ] ../src/consensus/aft/raft.h:2283     | Recv request vote response to [NODE 5] from [NODE 3]: they voted yes
```

**Comment by wintersteiger** [comment] 2021-04-01 10:23
Yes, @jumaffre and I added a few improvements for the failure reporting yesterday, but it's still too much. Generally, receiving messages after the channel is closed is fine, it shouldn't be a `[fail]`. 

However, I think there is still a bug related to node-to-node channels. Looking at node 0's log, I see this:

```
Node channel with dc1bbd50b8114fd00121df5c85d37ad904dc50623518a584380777fff01157fb is now established.
... (no mention of dc1...)
Node channel with dc1bbd50b8114fd00121df5c85d37ad904dc50623518a584380777fff01157fb cannot receive authenticated message: not yet established, status=0
```

I'll try and see whether I can get a local repro with verbose logs.

**Comment by wintersteiger** [comment] 2021-04-01 11:02
Yeah, there's at least one more bug in the channel destruction/recreation which would have the symptom that messages don't get sent the right way. Working on it.

**Comment by wintersteiger** [comment] 2021-04-07 12:11
I just managed to reproduce the original problem in a debug build running the code update test in virtual mode, but I still don't have a proper backtrace. It looks like `uv_close` is indeed called a second time, on a handle that's already in the closing state. There are only two calls to `uv_close` that are not protected by `if (uv_is_closing()) ...` and I'm trying to get a proper backtrace to find out how we get there.

**Comment by achamayou** [comment] 2021-05-12 09:21
No recent repro,

**Closed by achamayou** 2021-05-12 09:21 UTC
Labels: bug
