### ISSUE TITLE
ePBFT support for more than 1 node

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#266] opened 2019-07-19 13:13 UTC
As of https://github.com/microsoft/CCF/pull/263, CCF support PBFT with only 1 node (f = 0). CCF should support PBFT with f = 1, i.e. 4 nodes, to guarantee a full round of PBFT.

**Comment by ashamis** [comment] 2019-10-11 10:24
Duplicate of #359

**Closed** 2019-10-31 11:51 UTC
Labels: ePBFT integration
