### ISSUE TITLE
Append entries logic in pbft.h could be own class

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#753] opened 2020-01-30 11:05 UTC
Regarding #721 (https://github.com/microsoft/CCF/pull/721#discussion_r371884369) and the fact that we are using a set number (10) to batch append entries in pbft.h.

The tracking of append entry limits and the logic of sending them to other replicas could be made into its own class that could be handled by the `Replica` which could in turn send the new `Append_entries` messages with the indexes needed to the `Pbft` object to handle. This would eliminate the need for the `mark_stable` callback from `Replica` to `Pbft` that lets `Pbft` track the ledger index when we mark a sequence number as stable.

In that case it will be easier to add batching logic when sending append entries as we do in `raft` instead of having it hard-coded to 10.

**Comment by ashamis** [comment] 2020-03-03 14:17
Duplicate of https://github.com/microsoft/CCF/issues/691

**Closed by ashamis** 2020-03-03 14:17 UTC
Labels: enhancement
