### ISSUE TITLE
Pressure Measurement Question

### ISSUE THREAD

**Issue by taoyouxian** [microsoft/CCF#923] opened 2020-03-05 08:15 UTC
- Purpose
I make a test to see whether it affects `TPS` in CCF when I send `TX` repeatedly, because of the increasing memory in the enclave.
- Description
Using the sample `SmallBank`, I change the condition: do the test repeatedly with batch 20000 tx each, ignoring verifying the results.
With about one-hour pressure measurement, the client occurs `Transaction exception: GCM - Bad input parameters to function`, and the host log file shows `[info]../src/host/sigterm.h:24 -  - SIGTERM: Shutting down enclave gracefully...`. I doubt why it occurs `input parameters` after so many successful tx.

Additionally, other tests show `Received an outbound message for id (4) which is not a known connection` or `Shutting down enclave ` with the increasing data size in the message.

**Comment by achamayou** [comment] 2020-03-05 11:25
Hi @taoyouxian, could you share more information about what you have run to help us reproduce the issue?

In particular:

1. the hardware specs you are running this on
2. the command line used to start the network and the client
3. the nodes logs
4. the enclave configuration you used (oe_sign.conf)

We run performance tests in our CI on every commit, which you can find here for reference and comparison:

https://github.com/microsoft/CCF/blob/02f01ad036e8c213a7c8f00129446c0fde4e847d/CMakeLists.txt#L581
https://github.com/microsoft/CCF/blob/a4f8437c4d98675462d2a14bfff78cd4a423ce9c/samples/apps/smallbank/smallbank.cmake#L38

**Comment by taoyouxian** [comment] 2020-03-06 14:39
Hi @achamayou, thanks for answering. Let me give the detail of my test:

(1) pressure measurement:
The same config as the `smallbank`, I just do the test repeatedly with batch 20000 tx each and `WriteCheck` operation, ignoring verifying the results. See the following code updated in `perf_client.h` 
```
// perf_client.h
int count = 1;
double sum_time = 0;
auto time_last = (double)config_target["time"]; // maybe 10, but never complete for errors
double time = time_last * 3600 * 1000;
// Pre- and post- hooks allow derived classes to gather/log initial state
pre_creation_hook();
send_all_creation_transactions();
while(sum_time <= time) {
      post_creation_hook();
if (verifying)
{
//        verify_initial_state(verification_target["initial"]);
}
prepare_all_transactions();
pre_timing_body_hook();
if (verbosity >= 1)
{
//        std::cout << std::endl
//                  << "Sending " << num_transactions << " transactions from "
//                  << thread_count << " clients " << session_count << " times..."
//                  << std::endl;
}
auto timing_results = send_all_prepared_transactions();
if (verbosity >= 1)
{
//        std::cout << "Done" << std::endl;
}
post_timing_body_hook();
if (verifying)
{
//        verify_final_state(verification_target["final"]);
}

const auto dur_ms = summarize_results(timing_results, count);
sum_time += dur_ms;
std::cout << "time_now:" << sum_time / 1000 << "s" << std::endl;
std::cout << "time_run:" << time / 1000 << "s" << std::endl;
count++;
} 
```
and `small_bank_client.cpp`, make the fixed operation with `WriteCheck` for insert data:
```
// small_bank_client.cpp`
uint8_t operation =  (uint8_t)TransactionTypes::WriteCheck;
```
(2) Purpose:
To see whether it affects`TPS` in CCF when I send TX repeatedly, because of the increasing memory in the enclave.
(3) Nodes logs:
I have three different results after pressure measurement, and each reason is not very clear, such as:
1. I doubt why it occurs input parameters after so many successful tx, and the enclave is shut down gracefully.
```
// client logs
Transaction exception: GCM - Bad input parameters to function
```
2. I guess the problem of sending message, but not clear.
```
// host logs:
[info]../src/node/history.h:272 -  - Issuing signature at 827
[info]../src/node/history.h:272 -  - Issuing signature at 828
[fail]../src/host/rpcconnections.h:166 -  - Received an outbound message for id (4) which is not a known connection. Ignoring message of 108 bytes
[fail]../src/host/rpcconnections.h:166 -  - Received an outbound message for id (4) which is not a known connection. Ignoring message of 108 bytes
...
[info]../src/host/sigterm.h:24 -  - SIGTERM: Shutting down enclave gracefully...
```
3. Changing the size of data sended to the host:
```
case TransactionTypes::WriteCheck:
j["name"] = to_string(rand_range(total_accounts));
j["value"] = rand_range<int>(50);
j["k"] = rand_range_str<int>("10");   // random string with 10 size
```
The program is stopped , and I guess that it exceeds the heap size of enclave.

> Hi @taoyouxian, could you share more information about what you have run to help us reproduce the issue?
> 
> In particular:
> 
> 1. the hardware specs you are running this on
> 2. the command line used to start the network and the client
> 3. the nodes logs
> 4. the enclave configuration you used (oe_sign.conf)
> 
> We run performance tests in our CI on every commit, which you can find here for reference and comparison:
> 
> https://github.com/microsoft/CCF/blob/02f01ad036e8c213a7c8f00129446c0fde4e847d/CMakeLists.txt#L581
> 
> 
> https://github.com/microsoft/CCF/blob/a4f8437c4d98675462d2a14bfff78cd4a423ce9c/samples/apps/smallbank/smallbank.cmake#L38

Hi @achamayou, thanks for answering. Let me give the detail of my test:

(1) pressure measurement:
The same config as the `smallbank`, I just do the test repeatedly with batch 20000 tx each and `WriteCheck` operation, ignoring verifying the results. See the following code updated in `perf_client.h` 
```
// perf_client.h
int count = 1;
double sum_time = 0;
auto time_last = (double)config_target["time"]; // maybe 10, but never complete for errors
double time = time_last * 3600 * 1000;
// Pre- and post- hooks allow derived classes to gather/log initial state
pre_creation_hook();
send_all_creation_transactions();
while(sum_time <= time) {
      post_creation_hook();
if (verifying)
{
//        verify_initial_state(verification_target["initial"]);
}
prepare_all_transactions();
pre_timing_body_hook();
if (verbosity >= 1)
{
//        std::cout << std::endl
//                  << "Sending " << num_transactions << " transactions from "
//                  << thread_count << " clients " << session_count << " times..."
//                  << std::endl;
}
auto timing_results = send_all_prepared_transactions();
if (verbosity >= 1)
{
//        std::cout << "Done" << std::endl;
}
post_timing_body_hook();
if (verifying)
{
//        verify_final_state(verification_target["final"]);
}

const auto dur_ms = summarize_results(timing_results, count);
sum_time += dur_ms;
std::cout << "time_now:" << sum_time / 1000 << "s" << std::endl;
std::cout << "time_run:" << time / 1000 << "s" << std::endl;
count++;
} 
```
and `small_bank_client.cpp`, make the fixed operation with `WriteCheck` for insert data:
```
// small_bank_client.cpp`
uint8_t operation =  (uint8_t)TransactionTypes::WriteCheck;
```
(2) Purpose:
To see whether it affects`TPS` in CCF when I send TX repeatedly, because of the increasing memory in the enclave.
(3) Nodes logs:
I have three different results after pressure measurement, and each reason is not very clear, such as:
1. I doubt why it occurs input parameters after so many successful tx, and the enclave is shut down gracefully.
```
// client logs
Transaction exception: GCM - Bad input parameters to function
```
2. I guess the problem of sending message, but not clear.
```
// host logs:
[info]../src/node/history.h:272 -  - Issuing signature at 827
[info]../src/node/history.h:272 -  - Issuing signature at 828
[fail]../src/host/rpcconnections.h:166 -  - Received an outbound message for id (4) which is not a known connection. Ignoring message of 108 bytes
[fail]../src/host/rpcconnections.h:166 -  - Received an outbound message for id (4) which is not a known connection. Ignoring message of 108 bytes
...
[info]../src/host/sigterm.h:24 -  - SIGTERM: Shutting down enclave gracefully...
```
3. Changing the size of data sended to the host:
```
case TransactionTypes::WriteCheck:
j["name"] = to_string(rand_range(total_accounts));
j["value"] = rand_range<int>(50);
j["k"] = rand_range_str<int>("10");   // random string with 10 size
```
The program is stopped , and I guess that it exceeds the heap size of enclave.

**Comment by taoyouxian** [comment] 2020-03-06 14:39
> Hi @taoyouxian, could you share more information about what you have run to help us reproduce the issue?
> 
> In particular:
> 
> 1. the hardware specs you are running this on
> 2. the command line used to start the network and the client
> 3. the nodes logs
> 4. the enclave configuration you used (oe_sign.conf)
> 
> We run performance tests in our CI on every commit, which you can find here for reference and comparison:
> 
> https://github.com/microsoft/CCF/blob/02f01ad036e8c213a7c8f00129446c0fde4e847d/CMakeLists.txt#L581
> 
> 
> https://github.com/microsoft/CCF/blob/a4f8437c4d98675462d2a14bfff78cd4a423ce9c/samples/apps/smallbank/smallbank.cmake#L38

Hi @achamayou, thanks for answering. Let me give the detail of my test:

(1) pressure measurement:
The same config as the `smallbank`, I just do the test repeatedly with batch 20000 tx each and `WriteCheck` operation, ignoring verifying the results. See the following code updated in `perf_client.h` 
```
// perf_client.h
int count = 1;
double sum_time = 0;
auto time_last = (double)config_target["time"]; // maybe 10, but never complete for errors
double time = time_last * 3600 * 1000;
// Pre- and post- hooks allow derived classes to gather/log initial state
pre_creation_hook();
send_all_creation_transactions();
while(sum_time <= time) {
      post_creation_hook();
if (verifying)
{
//        verify_initial_state(verification_target["initial"]);
}
prepare_all_transactions();
pre_timing_body_hook();
if (verbosity >= 1)
{
//        std::cout << std::endl
//                  << "Sending " << num_transactions << " transactions from "
//                  << thread_count << " clients " << session_count << " times..."
//                  << std::endl;
}
auto timing_results = send_all_prepared_transactions();
if (verbosity >= 1)
{
//        std::cout << "Done" << std::endl;
}
post_timing_body_hook();
if (verifying)
{
//        verify_final_state(verification_target["final"]);
}

const auto dur_ms = summarize_results(timing_results, count);
sum_time += dur_ms;
std::cout << "time_now:" << sum_time / 1000 << "s" << std::endl;
std::cout << "time_run:" << time / 1000 << "s" << std::endl;
count++;
} 
```
and `small_bank_client.cpp`, make the fixed operation with `WriteCheck` for insert data:
```
// small_bank_client.cpp`
uint8_t operation =  (uint8_t)TransactionTypes::WriteCheck;
```
(2) Purpose:
To see whether it affects`TPS` in CCF when I send TX repeatedly, because of the increasing memory in the enclave.
(3) Nodes logs:
I have three different results after pressure measurement, and each reason is not very clear, such as:
1. I doubt why it occurs input parameters after so many successful tx, and the enclave is shut down gracefully.
```
// client logs
Transaction exception: GCM - Bad input parameters to function
```
2. I guess the problem of sending message, but not clear.
```
// host logs:
[info]../src/node/history.h:272 -  - Issuing signature at 827
[info]../src/node/history.h:272 -  - Issuing signature at 828
[fail]../src/host/rpcconnections.h:166 -  - Received an outbound message for id (4) which is not a known connection. Ignoring message of 108 bytes
[fail]../src/host/rpcconnections.h:166 -  - Received an outbound message for id (4) which is not a known connection. Ignoring message of 108 bytes
...
[info]../src/host/sigterm.h:24 -  - SIGTERM: Shutting down enclave gracefully...
```
3. Changing the size of data sended to the host:
```
case TransactionTypes::WriteCheck:
j["name"] = to_string(rand_range(total_accounts));
j["value"] = rand_range<int>(50);
j["k"] = rand_range_str<int>("10");   // random string with 10 size
```
The program is stopped , and I guess that it exceeds the heap size of enclave.

**Comment by achamayou** [comment] 2020-03-10 11:25
Hello @taoyouxian,

Thank you for the details. About problem 2. I think that's just the test setup timing out, it does send a SIGTERM to node when this happens.

I would like to know more about 3. in particular the return code and the log entries you observe in that case. I wouldn't think that running more transactions results in memory growth, because the state that's kept is per account, not per transaction.

I will try to reproduce these errors locally and will let you know what I find. May I suggest you run the same tests on a virtual build in the meantime to confirm whether you are hitting a problem with the code itself or with the fact that it's running in enclave?

**Comment by taoyouxian** [comment] 2020-03-12 19:21
Glad to hear from your reply @achamayou, thanks.
For problem 3, I think about two questions.

One is that each `j["name"]` means per account, and may the memory grows if I add one different account for the per transaction, and the state will increase. Each batch transactions: 20000 * Size(state of per account), for long-time pressure measurement, **can the enclave hold the memory or cause the TPS down**?

The other is that `n` batch transactions into the enclave, I calculate the data size: S * 20000 * n, `S = size(j["name"]) +size( j["value"]) + size(j["k"]`), `name` & `value` is the old params, and `k` is the one that I want to increase the transferring data into the enclave, maybe more than 50 or 100. As we know, the size of `EPC` is about 128M, and it can occur `page swap`, so does it matter? 

As above，I wonder whether the `TPS` can be influenced seriously for inserting data. 
When I do the tests, I see that the TPS has hundreds of gap fluctuations or even the enclave is shut down later, and I wonder if the increasing memory or just the inaccurate experiment.

**Comment by achamayou** [comment] 2020-06-25 15:18
@taoyouxian are you able to reproduce those results with a recent release of CCF?

**Comment by achamayou** [comment] 2020-08-17 13:08
Closing for now, but please re-open if this occurs on a recent release.

**Closed by achamayou** 2020-08-17 13:08 UTC
Labels: bug
